### ISSUE TITLE
Demo throwing 404 not found errors

### ISSUE THREAD

**Issue by tayden** [route360/r360-js#13]
The demo seems to be throwing not found errors as a result of the call to "http://api.route360.net/api_developers/v1/...". I'm getting this error with my own calls to the API also, so I suspect it's a bug in the API

**Comment by tayden** [comment]
Could be because http://developers.route360.net/download/basic/raphael-min.js isn't available

**Comment by gerbsen** [comment]
hey tayden,
thanks for your bug report, the default service url for the demo ist http://api.route360.net/api_dev. Could you tell me where you encountered this URL?

**Comment by tayden** [comment]
hey gerbsen,
At http://developers.route360.net/download/basic/basic_demo_key.html the browser console returns errors. r360.config.serviceUrl returns this address also.

**Comment by tayden** [comment]
Created pull request #14 which fixes the broken link. Not sure if it's a complete fix or not
