### ISSUE TITLE
setMap to null on polygon gives an zoom error

### ISSUE THREAD

**Issue by kafura** [route360/r360-js#16]
If I sets the map on a polygon to null, then it gives me an error when i'm zooming.

```javascript
var polygon = new GoogleMapsPolygonLayer(<google map>);
polygon.setMap(null);
```

The error is: 
```
Uncaught TypeError: Cannot read property 'getDiv' of null
```
![image](https://cloud.githubusercontent.com/assets/566659/8568623/a66cdb4a-256f-11e5-826e-a34f5de98d43.png)

I am trying to hide the polygon, is it the wrong way i'm doing it?

**Comment by j-slvr** [comment]
Consoder using ```polygon.div_.style.visibility = 'hidden';```

GoogleMapsPolygonLayer extends google.maps.OverlayView()
for further information on how to hide such an overlay please refer to https://developers.google.com/maps/documentation/javascript/examples/overlay-hideshow?hl=de
