### ISSUE TITLE
GeoJSON is not properly formatted

### ISSUE THREAD

**Issue by kofronpi** [route360/r360-js#23]
GeoJSON returned by the server is invalid and does not pass lint tests on `/france/v1/polygon` when specifying a geojson serializer.

> 
> Line 7: the first and last positions in a LinearRing of coordinates must be the same
> Line 75: the first and last positions in a LinearRing of coordinates must be the same
> Line 359: the first and last positions in a LinearRing of coordinates must be the same
> Line 659: the first and last positions in a LinearRing of coordinates must be the same
> Line 1123: the first and last positions in a LinearRing of coordinates must be the same
> Line 1351: the first and last positions in a LinearRing of coordinates must be the same
> Line 1395: the first and last positions in a LinearRing of coordinates must be the same
> Line 6703: the first and last positions in a LinearRing of coordinates must be the same
> [...]

Relevant spec from http://geojson.org/geojson-spec.html#polygon:

> A LinearRing is closed LineString with 4 or more positions. The first and last positions are equivalent (they represent equivalent points). Though a LinearRing is not explicitly represented as a GeoJSON geometry type, it is referred to in the Polygon geometry type definition.

**Comment by gerbsen** [comment]
Is this still happening?

**Comment by kofronpi** [comment]
Yes, although with less warnings than before.

**Comment by gerbsen** [comment]
Could you please provide a request URL?

**Comment by kofronpi** [comment]
> curl -X GET -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: 6e436dbe-49af-f3de-e793-ec1edd44548b" "https://service.route360.net/france/v1/polygon?cfg=%7B%22sources%22%3A%5B%7B%22lat%22%3A48.113844%2C%22lng%22%3A-1.681632%2C%22id%22%3A%22%22%2C%22tm%22%3A%7B%22car%22%3A%7B%7D%7D%7D%5D%2C%22elevation%22%3Atrue%2C%22polygon%22%3A%7B%22serializer%22%3A%22geojson%22%2C%22values%22%3A%5B1800%5D%7D%7D&key=YOUR_KEY"

**Comment by gerbsen** [comment]
Where do you test the geojson?

**Comment by gerbsen** [comment]
Well probably here right? http://geojsonlint.com/

**Comment by kofronpi** [comment]
Yes but I also try to import it into PostGIS to visualize it with QGIS and it fails because of the incorrect format, I have to "clean it up" before.

**Comment by gerbsen** [comment]
Okay, this is very strange. We are performing this repair operation also on our servers. We will look into this error. Thanks for bringing it up.

**Comment by gerbsen** [comment]
@kofronpi we just release an improved version of the geojson feature. could you test it again?

**Comment by gerbsen** [comment]
@kofronpi I just saw that you provided an example request url. I was able to retrieve this with the new version and loaded in qgis. So I'm closing this for now. In case the error persists, just reopen the issue!

`curl -X GET -H "Content-Type: application/json" -H "Cache-Control: no-cache" --compressed -H "Postman-Token: 6e436dbe-49af-f3de-e793-ec1edd44548b" "https://service.route360.net/france/v1/polygon?cfg=%7B%22sources%22%3A%5B%7B%22lat%22%3A48.113844%2C%22lng%22%3A-1.681632%2C%22id%22%3A%22%22%2C%22tm%22%3A%7B%22car%22%3A%7B%7D%7D%7D%5D%2C%22elevation%22%3Atrue%2C%22polygon%22%3A%7B%22serializer%22%3A%22geojson%22%2C%22values%22%3A%5B1800%5D%7D%7D&key=uhWrWpUhyZQy8rPfiC7X" > x.geojson`

![screenshot 2016-07-14 17 13 09](https://cloud.githubusercontent.com/assets/1186245/16844705/6bfcef30-49e6-11e6-8036-16e3ea204e1b.png)

**Comment by kofronpi** [comment]
@gerbsen it seems to work fine for now. I'll tell you if I find any new bugs ! :+1:  Did you guys change the area returned in the payload with this update ?

**Comment by gerbsen** [comment]
@kofronpi what exactly do you mean with "change the area"?
