### ISSUE TITLE
Any plans to enhance car travel times on peak hours ?

### ISSUE THREAD

**Issue by kofronpi** [route360/r360-js#31]
Right now car travel times are very optimistic and represent an average. 

Do you guys have any plans to enhance the result on peak hours ? 

On peak hours, effective travel times can be twofold compared to what r360 suggests. (I compared several results with google maps).

Thanks for the hard work !

**Comment by gerbsen** [comment]
hey @kofronpi, thanks for your feedback. yes currently we are using the actual street limits or the default limits per street class to calculate the averages. but we are also developing a peek travel time mode based on street density. (we do not have travel time data for actual osm edges, do you?) I client of us in australia tested this for the last couple of months and is quite happy with it, so we are trying to make this available for all endpoints. which ones would this be for you? can't really give you a timeline for this though.

Congestion demo: https://apps.route360.net/congestion/

**Comment by kofronpi** [comment]
Hi @gerbsen, I'm using the France endpoint. How do you get the data for Australia ? I don't know how to access the correct data in France yet !

**Comment by abenrob** [comment]
Hi @kofronpi - The congestion is available for australia at the /australia_congestion/ endpoint. We don't have the available for France yet, but given the requirement we could do so. Per help with the correct France data, shoot an email to support@route360.net, and give some details on what you are trying and what is not working, and I'll help you out.

**Comment by kofronpi** [comment]
@abenrob I'll get back to you soon about that, but I noticed that you added "peak hours" to your plans : 

> rush-hour modeling
> model travel times respecting peak travel periods - where available

Did you extend the coverage ? :)

**Comment by abenrob** [comment]
Yes - just a couple weeks back. Sorry for not updating.
The [West-Central Europe](https://developers.route360.net/coverage/westcentraleurope) endpoint now has that covered. THis can be enabled via the [travelOptions object](https://github.com/route360/r360-js/blob/master/src/util/TravelOptions.js#L551-L554)

**Comment by kofronpi** [comment]
@abenrob I don't understand how to set the parameter when querying with REST - it makes no difference in the output. Thank you !

**Comment by gerbsen** [comment]
hey @kofronpi, adam is on holiday, so I'll try to help you. Here is a CURL request to get polygons with rush-hour enabled. But please keep in mind that rush-hour mode is a paid/pro feature at the moment.

    curl -X POST \
      'https://service.route360.net/centraleurope/v1/polygon_post?key=YOUR_KEY_HERE' \
      -H 'content-type: application/json' \
      -d '{
    	"sources": [{
    		"lat": 52.516051,
    		"lng": 13.37776,
    		"id": "source0",
    		"tm": {
    			"car": {
    				"rushHour": true
    			}
    		}
    	}],
    	"elevation": true,
    	"edgeWeight": "time",
    	"polygon": {
    		"values": [300, 600, 900, 1200, 1500, 1800],
    		"intersectionMode": "union",
    		"serializer": "json",
    		"minPolygonHoleSize": 10000000
    	}
    }'

**Comment by kofronpi** [comment]
hey @gerbsen, thanks, I will only use it responsibly to try it out and see if it's adequate with our expectations. If we ever use it in production we'll definitely upgrade beforehand !
