### ISSUE TITLE
Routing on oceans

### ISSUE THREAD

**Issue by vladejs** [route360/r360-js#32]
Is there a way to calculate route for ships? I mean, given two points on map, calculate shortest (not mandatory) path without touching ground.

**Comment by gerbsen** [comment]
Theoretically we also use ferries provided by OSM. But I think they are disabled at the moment. What do you want to try? Do you have data for oceans? That would be extremely interesting to us! :)

**Comment by gerbsen** [comment]
Closing this for now, if you have further questions please reopen!
