### ISSUE TITLE
Make a proper release for server side use

### ISSUE THREAD

**Issue by gerbsen** [route360/r360-js#34]
- [] remove as many libs as possible
- [] make useable with node

**Comment by CraigglesO** [comment]
Are you saying that you are willing to let me host my own r360 server? I would happily help as it would benefit my own project immensely.
-Craig.

**Comment by gerbsen** [comment]
We are currently implementing a new modern/modular version of the JS api. This will become available to the public later this month. If you want to host our service on your servers just contact our sales team: https://www.route360.net/contact 
Cheers, Daniel
