### ISSUE TITLE
Add rush-hour as alias for congestion

### ISSUE THREAD

**Issue by gerbsen** [route360/r360-js#35]
We need to keep the old congestion but need to add the alias 
https://code.route360.net/api-server/r360-service/issues/38

**Comment by gerbsen** [comment]
please make the enableCongestion method depricated

**Comment by imtezcan** [comment]
Available in version v0.3.2: https://github.com/route360/r360-js/commit/40926250b838cc4ff2902c8dcaf72127d5763896
