### ISSUE TITLE
Publish all versions to NPM

### ISSUE THREAD

**Issue by mijamo** [route360/r360-js#36]
Currently, the last version on NPM is `0.3.2`. In the github repo it seems to be `0.3.4`.

It would be nice to publish all the version to NPM, so that people like me who would want to install the version from NPM can always have the latest version.

In addition, it would be nice to switch to SemVer once the library is considered stable. Right now 0.3.3 added feature compared to 0.3.2 which is counter-intuitive.

**Comment by gerbsen** [comment]
hey mijamo, thanks for raising this issue. we will push this to nom! you mean it should be 0.4.0?

**Comment by gerbsen** [comment]
@abenrob could you also please integrate this into the release documentation?

**Comment by mijamo** [comment]
Yes I think 0.4.0 should be more appropriate for adding a new feature. 

Thank you for the very quick answer.

**Comment by abenrob** [comment]
Good point @mijamo I'll re-version, and publish today

**Comment by abenrob** [comment]
v0.4.0 published. Will go back and back-publish 0.3.3 and 0.3.4, but not today.

**Comment by abenrob** [comment]
Not feeling that is't necessary to publish all outdated version to npm. @gerbsen re-open if you feel differently.
