### ISSUE TITLE
Independent travel times for sources - PolygonService geometry operations

### ISSUE THREAD

**Issue by kofronpi** [route360/r360-js#41]
Hello,
In the [PolygonService documentation](https://developers.route360.net/services/polygon.html), you describe how to mix travel types (car, walk, bike...) in geometry operations such as union & intersection.

You also explain how to set travel times.
However, I don't think you can **set different travel times** for each source point, for instance to find out how far you can go in bike in 20 minutes versus in a car in 40 minutes, in peak hours or not.

Waiting for your feedback on this one, but I have the feeling I'll have to do my own intersection for now :)

Thanks !

**Comment by gerbsen** [comment]
hey @kofronpi , sorry for the slow response. you are right, this is currently not possible. what is the use case to intersect 20min bike with 40 minutes car? this is certainly a feature we could implement for you.

**Comment by kofronpi** [comment]
Hi @gerbsen, no worries, I know I have a lot of questions ;)

The use case : know what's accessible for different people at a given time, with different travel modes. Think accessibility apps. So yes, I will be doing point in polygon search with the result... Right now I'm prototyping with TimeService so maybe this is more appropriate, but I still need the different modes / different time travels :) Would TimeService be capable of doing that ?

Thanks !

**Comment by gerbsen** [comment]
Sure thing, the TimeService is much more precise then point-in-polygon test. So you can just route to 3600s for both travel types and then filter via your preferred programming language different for each source.

**Comment by gerbsen** [comment]
Or just perform multiple requests. :)

**Comment by abenrob** [comment]
This is blocked by enhancement need on the rest service itself. Closing as there is nothing that can be done without service update.
