### ISSUE TITLE
Support for other countries?

### ISSUE THREAD

**Issue by giorgim** [route360/r360-js#42]
Is there support for (or is it planned to support) country Georgia? (https://en.wikipedia.org/wiki/Georgia_(country))
or maybe you are aware of other libraries/plugins for that?

**Comment by gerbsen** [comment]
hey @giorgim, thanks for your interest in our technology. we do not support georgia, yet. If you really need that we can set this up for you if you sign up for one of our plans. Just contact our support here: https://www.route360.net/contact
