### ISSUE TITLE
Enhancement: Removing jQuery dependency

### ISSUE THREAD

**Issue by casperfibaek** [route360/r360-js#51]
Is it possible to remove the jQuery dependency? In many modern apps, jQuery is no longer the framework of choice. Looking through the source, it does not appear to be used a lot - mainly the ajax functionality.

**Comment by gerbsen** [comment]
hey @casperfibaek we are currently working on a more modern version of this library. it's not yet public yet, but can't be long :) If you need this ASAP, there is definitely something that we can work out.
